### ISSUE TITLE
general question about your experience building this project

### ISSUE THREAD

**Issue by ghost** [nsdahile/password-manager#1]
Hi @nsdahile  ,

Hope you are all well !

I would like to create a clone of [teampass](https://github.com/nilsteampassnet/TeamPass) a collaborative password manager, and I was wondering if you knew or can explain how to create a catalog of items, organised with an [animated tree view](https://github.com/embraceitmobile/animated_tree_view), and [flutter_rbac](https://github.com/wilpar/flutter_rbac) for managing roles and permissions. From your experience, what advices would you give me for neat architecture.

Thanks for any insights or inputs on that question.

teampass screeenshot:
![pf_tp_5](https://user-images.githubusercontent.com/1963546/143676762-88e5e5c0-6a3e-473f-adae-09d9ae274f18.png)

Cheers,
Luc

**Comment by nsdahile** [comment]
For UI as you want to use [animated_tree_view](https://github.com/embraceitmobile/animated_tree_view) you need data to be stored in form of tree, as per your requirement **n-array tree** should be used. 

For managing roles and permissions you need to save different type of user and crosscheck that before performing any operation. For example you are using firebase then your app should only request those services that suites to type of that user and also you should crosscheck that request on firebase by using firebase functions (a node.js based feature) or set rules on firebase database. This will allow you to manage roles and their permission.

For neat architecture you should keep your data models, app logic ,UI part separate and update your UI according to change in data which you can do by using **Provider/GetX/Blocks** flutter packages. You can use MVC model.
